name: Update Tokens

on:
  pull_request:
    paths:
      - "**/*.json"

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git Version Beta
        id: version
        if: ${{ startsWith(github.event.pull_request.head.ref, 'zeroheight-tokens-') }}
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Configure Yarn
        shell: bash
        run: |
          yarn set version 4.0.2

      - name: Build App
        shell: bash
        run: yarn install

      - name: Run Token Update Script
        run: yarn update-tokens

      - name: Commit Changes
        run: |
          git add ./src/build
          git commit -m "Update tokens"
          git push
