name: Update Tokens

on: workflow_dispatch

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Fetch Token JSON
        run: |
          TOKEN_URL="https://untitled-team-978fr.zeroheight.com/api/token_management/token_set/4736/export?format=style-dictionary"
          curl -o ./tokens/token.json "$TOKEN_URL"
          cat ./tokens/token.json

      - name: Create release branch and update tokens
        if: success()
        run: |
          if git diff --exit-code --quiet; then
            echo "No changes detected"
          else
            BRANCH_NAME="feature/update-zeroheight-tokens-$(date +'%Y%m%d%H%M')"
            git checkout -b $BRANCH_NAME

            yarn install
            yarn update-tokens

            git config --global user.email "hanadul34@wevwersecompany.com"
            git config --global user.name "hana"
            git add .
            git commit -m "Update tokens!"
            git push --set-upstream origin $BRANCH_NAME -f

            PR_TITLE="Automatic PR - Update token - $(date +'%Y%m%d%H%M')"
            echo "PR title: $PR_TITLE"
            gh pr create --base develop --head $BRANCH_NAME --title "$PR_TITLE" --body "This PR is automatically created to update the token."
          fi
