name: Update Tokens

on:
  pull_request:
    types: opened

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build App
        shell: bash
        run: yarn install

      - name: Run Token Update Script
        run: yarn update-tokens

      - name: Commit Changes
        run: |
          git config --global user.email "hanadul34@weversecompany.com"
          git config --global user.name "hanaIm"
          git add .
          git commit -m "Update tokens"
          git push
