name: Update Tokens
on:
  pull_request:
    types: [opened]
    paths:
      - "/tokens/token.json"
    branches:
      - "zeroheight-tokens-*"

jobs:
  update-tokens:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test'
    
